### ISSUE TITLE
Add support for other APIs

### ISSUE THREAD

**Issue by agladysh** [catwell/fakeredis#1]
It is nice to have redis-lua API built in, but there are other Redis client libraries with different semantics (for example, lua-resty-redis, my lua-hiredis etc.). 

Wrapping redis-lua API in a proxy code to support other APIs would be weird and quirky. Please add a low-level API so anyone will be able to code their API on top of that.

**Comment by spemmons** [comment]
it would also be nice if "fakeredis" supported the "hiredis" gem

**Comment by catwell** [comment]
@spemmons Gem? Are you looking for the Ruby fakeredis project? This is the one for Lua.

**Comment by spemmons** [comment]
Ah. My mistake. Thanks for the clarification.

**Comment by catwell** [comment]
I no longer use this module actively and do not intend to do this.
